### ISSUE TITLE
Error when running 'npm run emul-android'

### ISSUE THREAD

**Issue by j-krl** [supertorpe/chessendgametraining#33]
Hi, I'm interested in getting involved with this project but I keep getting an error when I try to run the `npm run emul-android` script. I have no experience using Ionic or doing mobile dev so it's possible I am missing something obvious.

`npm run start` works fine and I can get the webapp going. Here's the output I get when trying to emulate Android in verbose mode:

```
> cordova build android --emulator
Source path does not exist: resources\android\icon\drawable-hdpi-icon.png
[ERROR] An error occurred while running subprocess cordova.

        cordova build android --emulator exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.
npm verb lifecycle chessendgames@2.3.2~emul-android: unsafe-perm in lifecycle true
npm verb lifecycle chessendgames@2.3.2~emul-android: PATH: /Users/jkrl/.nvm/versions/node/v14.0.0/lib/node_mo
dules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/jkrl/Programs/chessendgametraining/node_modules/.bin
:/Users/jkrl/.nvm/versions/node/v14.0.0/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/
opt/mongodb-community@4.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/jkrl/.nvm/vers
ions/node/v14.0.0/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/opt/mongodb-community@
4.0/bin:/opt/anaconda3/bin:/opt/anaconda3/condabin
npm verb lifecycle chessendgames@2.3.2~emul-android: CWD: /Users/jkrl/Programs/chessendgametraining

npm info lifecycle chessendgames@2.3.2~emul-android: Failed to exec emul-android script
npm verb stack Error: chessendgames@2.3.2 emul-android: `ionic cordova emulate android`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/Users/jkrl/.nvm/versions/node/v14.0.0/lib/node_modules/npm/n
ode_modules/npm-lifecycle/index.js:332:16)
npm verb stack     at EventEmitter.emit (events.js:315:20)
npm verb stack     at ChildProcess.<anonymous> (/Users/jkrl/.nvm/versions/node/v14.0.0/lib/node_modules/npm/n
ode_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:315:20)
npm verb stack     at maybeClose (internal/child_process.js:1051:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
npm verb pkgid chessendgames@2.3.2
npm verb cwd /Users/jkrl/Programs/chessendgametraining
npm verb Darwin 17.7.0
npm verb argv "/Users/jkrl/.nvm/versions/node/v14.0.0/bin/node" "/Users/jkrl/.nvm/versions/node/v14.0.0/bin/n
pm" "run" "emul-android" "--verbose"
npm verb node v14.0.0
npm verb npm  v6.14.4
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! chessendgames@2.3.2 emul-android: `ionic cordova emulate android`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the chessendgames@2.3.2 emul-android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
npm timing npm Completed in 41754ms
```
The path `resources\android\icon\drawable-hdpi-icon.png` definitely exists so it's possibly running from the wrong root but I can't tell where. I am running `npm run emul-android` from the 'chessendgametraining' project directory.

Thanks!

**Comment by supertorpe** [comment]
I'm not sure the reason for the error.
Try launching "npm run build-icons" first.
